DataMarketFE/Controllers/BusinessController.cs
using System.Threading.Tasks;
using DataMarketFE.APIs;
using DataMarketFE.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DataMarketFE.Controllers
{
    [Route("/[controller]")]
    public class BusinessController : Controller
    {
        private readonly DataMarketApiClient _dataMarketApiClient;

        public BusinessController(DataMarketApiClient dataMarketApiClient)
        {
            _dataMarketApiClient = dataMarketApiClient;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            ViewBag.Market = true;
            ViewBag.LoggedIn = HttpContext.IsUserLoggedIn();

            return View();
        }     

        [HttpPost]
        public async Task<IActionResult> Create(BusinessInquery model)
        {
            ViewBag.LoggedIn = HttpContext.IsUserLoggedIn();

            if (!ModelState.IsValid)
            {
                return View("Index", model);
            }
            else
            {
                await _dataMarketApiClient.PostAsync("https://hooks.zapier.com/hooks/catch/2808065/8btp41/", model);
                TempData["flash-success-msg"] = "We received your request and will contact you shortly.";
                return Redirect("/");
            }
        }       
    }
}

DataMarketFE/Views/Business/Description.cshtml
    <h3 class="title is-3">
        DataCircle assists companies managing their Data Assets.
    </h3>
    <br />
    <h3 class="subtitle is-4">
        Take advantage of our world-wide network in order to make strategic purchases of information that you need for your Growth,
        R&D, daily Business Development.
    </h3>
    <br />
    <h3 class="subtitle is-4">
        Connect with us, to free isolated data silos, monetize existing data and reveal the value of your data.
    </h3>

    <br />

    <h3 class="title is-3">
        Give us a short description and we will contact you immediately. 👉
    </h3>

DataMarketFE/Views/Business/Form.cshtml
 @model DataMarketFE.ViewModels.BusinessInquery

<div class="card is-shadowless is-primary">
    <form asp-controller="Business" asp-action="Create" asp-route-returnurl="@ViewData[" ReturnUrl "]" method="post" class="form-horizontal">
        <div class="card-content is-paddingless">
            <div class="content">
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.Buy)

                <div asp-validation-summary="All" class="has-text-centered has-text-danger"></div>
                <br/>

                <p class="field has-text-centered">
                    <a id="btnBuy" class="button is-medium is-primary">
                        <span class="icon">
                        <i class="fa Example of shopping-cart fa-shopping-cart "></i>
                        </span>
                        <span>Buy</span>
                    </a>
                    <a id="btnSell" class="button is-medium">
                        <span class="icon">
                        <i class="fa fa-usd"></i>
                        </span>
                        <span>Sell</span>
                    </a>
                </p>

                <script>
                    $('#Buy').val("true");

                    $('#btnBuy').on('click', function () {
                        if (!$("#btnBuy").hasClass("is-primary")) {
                            $('#btnBuy').addClass('is-primary');
                            $('#btnSell').removeClass('is-primary');
                        }

                        $('#Buy').val("true");
                    })
                    $('#btnSell').on('click', function () {
                        if (!$("#btnSell").hasClass("is-primary")) {
                            $('#btnSell').addClass('is-primary');
                            $('#btnBuy').removeClass('is-primary');
                        }

                        $('#Buy').val("false");
                    })
                </script>

                <div class="field">
                    <div class="control">
                        <textarea class="textarea" placeholder="Please describe shortly the dataset in question." asp-for="Description" rows="5" required>

                        </textarea>
                        <span asp-validation-for="Description" class="has-text-danger"></span>
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <input class="input is-medium" placeholder="The price can be a total or per size/row/lead" asp-for="Price" required>
                        <span asp-validation-for="Price" class="has-text-danger"></span>
                    </div>
                </div>
                <div class="field">
                    <div class="control has-icons-left">
                        <input class="input is-medium" type="email" placeholder="Email" asp-for="Email" required>
                        <span asp-validation-for="Email" class="has-text-danger"></span>

                        <span class="icon is-small is-left">
                            <i class="fa fa-envelope"></i>
                        </span>
                    </div>
                </div>

                <br />

                <div class="field">
                    <p class="control has-text-centered">
                        <button type="submit" class="button is-success is-outlined is-medium">Submit</button>
                    </p>
                </div>
            </div>
        </div>
    </form>
    <br />
    <div class="column has-text-centered">
        <h4 class="subtitle is-5"> Or contact us via the online chat 💬 or via
            <a href="mailto:support@datacircle.io" class="btn btn-simple btn-primary btn-lg">Email 📧</a>
        </h4>
    </div>
</div>

DataMarketFE/Views/Business/Index.cshtml
@{ ViewData["Title"] = "Business"; }

<section class="hero is-white is-fullheight">
    <div class="hero-body">
        <div class="container">
            <div class="columns">
                <div class="column is-6">
                    @Html.Partial("Description")
                </div>
                <div class="column is-6">
                    @Html.Partial("Form")
                </div>
            </div>
        </div>
    </div>
</section>